apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: 21555e846065481e4faa1c55ae1a3afa3578037656154a827d7542139a02b2aa
  creationTimestamp: "2024-12-30T09:24:04Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    operator.tekton.dev/operand-name: tektoncd-pipelines
    pipeline.tekton.dev/release: v0.65.4
    version: v0.65.4
  name: clustertasks.tekton.dev
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonPipeline
    name: pipeline
    uid: 47cb9b8d-f31b-4464-ac21-ef0df4bb1934
  resourceVersion: "8118389"
  uid: 772b5202-8c00-4d86-a0f4-caac20707564
spec:
  conversion:
    strategy: None
  group: tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    kind: ClusterTask
    listKind: ClusterTaskList
    plural: clustertasks
    singular: clustertask
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-pipelines
    kind: ClusterTask
    listKind: ClusterTaskList
    plural: clustertasks
    singular: clustertask
  conditions:
  - lastTransitionTime: "2024-12-30T09:24:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-30T09:24:04Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
