apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: 50414516adfd690938780bd031dd5f545fe055b6949d1de7cb6c491f1cdfdaab
  creationTimestamp: "2024-12-30T09:24:53Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    operator.tekton.dev/operand-name: tektoncd-triggers
    triggers.tekton.dev/release: v0.30.0
    version: v0.30.0
  name: interceptors.triggers.tekton.dev
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonTrigger
    name: trigger
    uid: 4ca66f38-f13a-47e0-8d6e-5b7f76f3f2a1
  resourceVersion: "8119294"
  uid: 7634cbc3-163f-4c21-b922-6bb4c4fed4b3
spec:
  conversion:
    strategy: None
  group: triggers.tekton.dev
  names:
    categories:
    - tekton
    - tekton-triggers
    kind: Interceptor
    listKind: InterceptorList
    plural: interceptors
    shortNames:
    - ni
    singular: interceptor
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-triggers
    kind: Interceptor
    listKind: InterceptorList
    plural: interceptors
    shortNames:
    - ni
    singular: interceptor
  conditions:
  - lastTransitionTime: "2024-12-30T09:24:53Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-30T09:24:53Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
