apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operatorframework.io/installed-alongside-5c7d0e97cdfb5409: openshift-operators/kiali-operator.v1.89.8
  creationTimestamp: "2024-12-16T03:00:27Z"
  generation: 1
  labels:
    app: kiali-operator
    olm.managed: "true"
    operators.coreos.com/kiali-ossm.openshift-operators: ""
  name: kialis.kiali.io
  resourceVersion: "35946"
  uid: 175bc397-9281-46f2-9d12-0bf6d027c5d6
spec:
  conversion:
    strategy: None
  group: kiali.io
  names:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  conditions:
  - lastTransitionTime: "2024-12-16T03:00:27Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-16T03:00:27Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
