apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operatorframework.io/installed-alongside-5c7d0e97cdfb5409: openshift-operators/kiali-operator.v1.89.8
  creationTimestamp: "2024-12-16T03:00:27Z"
  generation: 1
  labels:
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    olm.managed: "true"
    operators.coreos.com/kiali-ossm.openshift-operators: ""
  name: ossmconsoles.kiali.io
  resourceVersion: "35948"
  uid: 1ae9800a-807a-4f5f-8f29-8406f2222023
spec:
  conversion:
    strategy: None
  group: kiali.io
  names:
    kind: OSSMConsole
    listKind: OSSMConsoleList
    plural: ossmconsoles
    singular: ossmconsole
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: OSSMConsole
    listKind: OSSMConsoleList
    plural: ossmconsoles
    singular: ossmconsole
  conditions:
  - lastTransitionTime: "2024-12-16T03:00:27Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-16T03:00:27Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
