apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.openshift.io: https://github.com/openshift/api/pull/751
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  creationTimestamp: "2024-12-16T02:30:23Z"
  generation: 1
  name: rangeallocations.security.internal.openshift.io
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 4be87693-1e87-4de1-bfa7-e660ed3a08c1
  resourceVersion: "641"
  uid: 19f8d714-861a-4b2f-a74b-683f13a2fec2
spec:
  conversion:
    strategy: None
  group: security.internal.openshift.io
  names:
    kind: RangeAllocation
    listKind: RangeAllocationList
    plural: rangeallocations
    singular: rangeallocation
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: "RangeAllocation is used so we can easily expose a RangeAllocation
          typed for security group This is an internal API, not intended for external
          consumption. \n Compatibility level 1: Stable within a major release for
          a minimum of 12 months or 3 minor releases (whichever is longer)."
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          data:
            description: data is a byte array representing the serialized state of
              a range allocation.  It is a bitmap with each bit set to one to represent
              a range is taken.
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          range:
            description: range is a string representing a unique label for a range
              of uids, "1000000000-2000000000/10000".
            type: string
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: RangeAllocation
    listKind: RangeAllocationList
    plural: rangeallocations
    singular: rangeallocation
  conditions:
  - lastTransitionTime: "2024-12-16T02:30:23Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-16T02:30:23Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
