apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: fbd370969afc5a8e6eb92a04568942e907233111512ea43cdeaae605c1f22f7e
  creationTimestamp: "2024-12-30T09:24:04Z"
  generation: 3
  labels:
    operator.tekton.dev/operand-name: tektoncd-pipelines
    resolution.tekton.dev/release: devel
  name: resolutionrequests.resolution.tekton.dev
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonPipeline
    name: pipeline
    uid: 47cb9b8d-f31b-4464-ac21-ef0df4bb1934
  resourceVersion: "14151475"
  uid: 52f498ed-c2e3-48f5-a3e2-25b727d70200
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN6VENDQW5PZ0F3SUJBZ0lRQTBYTG1ySG5HYmNkM2RLelg3K1piVEFLQmdncWhrak9QUVFEQWpCUk1SUXcKRWdZRFZRUUtFd3RyYm1GMGFYWmxMbVJsZGpFNU1EY0dBMVVFQXhNd2RHVnJkRzl1TFhCcGNHVnNhVzVsY3kxMwpaV0pvYjI5ckxtOXdaVzV6YUdsbWRDMXdhWEJsYkdsdVpYTXVjM1pqTUI0WERUSTFNREV3TlRFMU1qUXpObG9YCkRUSTFNREV4TWpFMU1qUXpObG93VVRFVU1CSUdBMVVFQ2hNTGEyNWhkR2wyWlM1a1pYWXhPVEEzQmdOVkJBTVQKTUhSbGEzUnZiaTF3YVhCbGJHbHVaWE10ZDJWaWFHOXZheTV2Y0dWdWMyaHBablF0Y0dsd1pXeHBibVZ6TG5OMgpZekJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQXVJNEQ1bWEweUZaak8zZ3NyWkVUemZRZG84CnVhc0g0UkxlbElqdXBvSUpPeGNoalQ5a0VER3lWakhKNnNSb2R2RmIzbG9QUHhZSWlLZ095RVI3YTBpamdnRXIKTUlJQkp6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRgpCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkkwWFZTeHlyRkU2MG4xVitLaGxmNzQ0CjhDVFVNSUhGQmdOVkhSRUVnYjB3Z2JxQ0dIUmxhM1J2Ymkxd2FYQmxiR2x1WlhNdGQyVmlhRzl2YTRJc2RHVnIKZEc5dUxYQnBjR1ZzYVc1bGN5MTNaV0pvYjI5ckxtOXdaVzV6YUdsbWRDMXdhWEJsYkdsdVpYT0NNSFJsYTNSdgpiaTF3YVhCbGJHbHVaWE10ZDJWaWFHOXZheTV2Y0dWdWMyaHBablF0Y0dsd1pXeHBibVZ6TG5OMlk0SStkR1ZyCmRHOXVMWEJwY0dWc2FXNWxjeTEzWldKb2IyOXJMbTl3Wlc1emFHbG1kQzF3YVhCbGJHbHVaWE11YzNaakxtTnMKZFhOMFpYSXViRzlqWVd3d0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKdWo3Qm1rZXZWVFQrN1NIOUg5bnRyVQpmSFVqczlPL2RCb3RiVjZzVUZFOEFpQXVtYVdkM09zMDBLTjRTZkQ5b3dWMWt3SXh2am9hZEY4NEczSDJJR09XCjZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        service:
          name: tekton-pipelines-webhook
          namespace: openshift-pipelines
          path: /resource-conversion
          port: 443
      conversionReviewVersions:
      - v1alpha1
      - v1beta1
  group: resolution.tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    kind: ResolutionRequest
    listKind: ResolutionRequestList
    plural: resolutionrequests
    shortNames:
    - resolutionrequest
    - resolutionrequests
    singular: resolutionrequest
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].reason
      name: Reason
      type: string
    deprecated: true
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .metadata.ownerReferences[0].kind
      name: OwnerKind
      type: string
    - jsonPath: .metadata.ownerReferences[0].name
      name: Owner
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].reason
      name: Reason
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: StartTime
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].lastTransitionTime
      name: EndTime
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-pipelines
    kind: ResolutionRequest
    listKind: ResolutionRequestList
    plural: resolutionrequests
    shortNames:
    - resolutionrequest
    - resolutionrequests
    singular: resolutionrequest
  conditions:
  - lastTransitionTime: "2024-12-30T09:24:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-30T09:24:04Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
