apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  creationTimestamp: "2024-12-16T06:03:48Z"
  generation: 1
  labels:
    app: istio-pilot
    heritage: Tiller
    istio: rbac
    maistra-version: 2.4.13
    release: istio
  name: servicemeshrbacconfigs.rbac.maistra.io
  resourceVersion: "103385"
  uid: fa99c034-7c12-4cb5-ac41-6cb519e8ba66
spec:
  conversion:
    strategy: None
  group: rbac.maistra.io
  names:
    categories:
    - istio-io
    - rbac-istio-io
    kind: ServiceMeshRbacConfig
    listKind: ServiceMeshRbacConfigList
    plural: servicemeshrbacconfigs
    singular: servicemeshrbacconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Configuration for Role Based Access Control. See more details
              at: https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1.html'
            properties:
              enforcementMode:
                enum:
                - ENFORCED
                - PERMISSIVE
                type: string
              exclusion:
                description: A list of services or namespaces that should not be enforced
                  by Istio RBAC policies.
                properties:
                  namespaces:
                    description: A list of namespaces.
                    items:
                      format: string
                      type: string
                    type: array
                  services:
                    description: A list of services.
                    items:
                      format: string
                      type: string
                    type: array
                type: object
              inclusion:
                description: A list of services or namespaces that should be enforced
                  by Istio RBAC policies.
                properties:
                  namespaces:
                    description: A list of namespaces.
                    items:
                      format: string
                      type: string
                    type: array
                  services:
                    description: A list of services.
                    items:
                      format: string
                      type: string
                    type: array
                type: object
              mode:
                description: Istio RBAC mode.
                enum:
                - "OFF"
                - "ON"
                - ON_WITH_INCLUSION
                - ON_WITH_EXCLUSION
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - istio-io
    - rbac-istio-io
    kind: ServiceMeshRbacConfig
    listKind: ServiceMeshRbacConfigList
    plural: servicemeshrbacconfigs
    singular: servicemeshrbacconfig
  conditions:
  - lastTransitionTime: "2024-12-16T06:03:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-16T06:03:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
