apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    api-approved.kubernetes.io: https://github.com/kubernetes/community/pull/2524
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  creationTimestamp: "2024-12-16T02:31:05Z"
  generation: 1
  name: storageversionmigrations.migration.k8s.io
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
    uid: 4be87693-1e87-4de1-bfa7-e660ed3a08c1
  resourceVersion: "730"
  uid: 7f86ea3e-1442-41ca-ba07-560cc2b6d1d8
spec:
  conversion:
    strategy: None
  group: migration.k8s.io
  names:
    kind: StorageVersionMigration
    listKind: StorageVersionMigrationList
    plural: storageversionmigrations
    singular: storageversionmigration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: StorageVersionMigration represents a migration of stored data
          to the latest storage version.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Specification of the migration.
            properties:
              continueToken:
                description: The token used in the list options to get the next chunk
                  of objects to migrate. When the .status.conditions indicates the
                  migration is "Running", users can use this token to check the progress
                  of the migration.
                type: string
              resource:
                description: The resource that is being migrated. The migrator sends
                  requests to the endpoint serving the resource. Immutable.
                properties:
                  group:
                    description: The name of the group.
                    type: string
                  resource:
                    description: The name of the resource.
                    type: string
                  version:
                    description: The name of the version.
                    type: string
                type: object
            required:
            - resource
            type: object
          status:
            description: Status of the migration.
            properties:
              conditions:
                description: The latest available observations of the migration's
                  current state.
                items:
                  description: Describes the state of a migration at a certain point.
                  properties:
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: StorageVersionMigration
    listKind: StorageVersionMigrationList
    plural: storageversionmigrations
    singular: storageversionmigration
  conditions:
  - lastTransitionTime: "2024-12-16T02:31:05Z"
    message: approved in https://github.com/kubernetes/community/pull/2524
    reason: ApprovedAnnotation
    status: "True"
    type: KubernetesAPIApprovalPolicyConformant
  - lastTransitionTime: "2024-12-16T02:31:05Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-16T02:31:05Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
