apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: 7ef6f48a279562f50f1ba2f16494131706d98f89b833621cf72f6368f80ba389
  creationTimestamp: "2024-12-30T09:24:54Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    operator.tekton.dev/operand-name: tektoncd-triggers
    triggers.tekton.dev/release: v0.30.0
    version: v0.30.0
  name: triggerbindings.triggers.tekton.dev
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonTrigger
    name: trigger
    uid: 4ca66f38-f13a-47e0-8d6e-5b7f76f3f2a1
  resourceVersion: "8119303"
  uid: d426fc34-28e0-48c1-8ff1-f2ef4109ff08
spec:
  conversion:
    strategy: None
  group: triggers.tekton.dev
  names:
    categories:
    - tekton
    - tekton-triggers
    kind: TriggerBinding
    listKind: TriggerBindingList
    plural: triggerbindings
    shortNames:
    - tb
    singular: triggerbinding
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-triggers
    kind: TriggerBinding
    listKind: TriggerBindingList
    plural: triggerbindings
    shortNames:
    - tb
    singular: triggerbinding
  conditions:
  - lastTransitionTime: "2024-12-30T09:24:54Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-30T09:24:54Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
