apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    operator.tekton.dev/last-applied-hash: 1dd7129ad1ed2eb9cecdcf6389c59c8f0ec7331544c8efe3a52cee2fb9c7878d
  creationTimestamp: "2024-12-30T09:24:54Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    operator.tekton.dev/operand-name: tektoncd-triggers
    triggers.tekton.dev/release: v0.30.0
    version: v0.30.0
  name: triggertemplates.triggers.tekton.dev
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonTrigger
    name: trigger
    uid: 4ca66f38-f13a-47e0-8d6e-5b7f76f3f2a1
  resourceVersion: "8119307"
  uid: 405bce46-167d-4cd0-b19a-022b1e79dcd3
spec:
  conversion:
    strategy: None
  group: triggers.tekton.dev
  names:
    categories:
    - tekton
    - tekton-triggers
    kind: TriggerTemplate
    listKind: TriggerTemplateList
    plural: triggertemplates
    shortNames:
    - tt
    singular: triggertemplate
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - tekton
    - tekton-triggers
    kind: TriggerTemplate
    listKind: TriggerTemplateList
    plural: triggertemplates
    shortNames:
    - tt
    singular: triggertemplate
  conditions:
  - lastTransitionTime: "2024-12-30T09:24:54Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2024-12-30T09:24:54Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1
