name: Test

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.19"
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -race -v ./...
